services:
  redis-cart:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  cartservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.5
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379
    depends_on:
      - redis-cart
    restart: unless-stopped